# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the portfolio effect and other metrics from a simulation
#' system
#'
#' This function takes the output from \code{\link{paradox_sim}}
#' (minus the row containing the effort time series) and
#' calculates various portfolio effect metrics. It is implemented in
#' C++ for speed.
#' 
#' @param x The matrix minus the effort row
#' @param num_pop Number of populations
#' @param t_end Number of years (after removing the burn-in period
#' yourself).
#' @export
#' @return
#' A named list with the elements: \code{pe} (portfolio effect), \code{sd_ts}
#' (vector of standard deviations for the populations), \code{mean_ts} (vector
#' of means for the subpopulations), \code{sd_total} (standard deviation of
#' the total biomass), \code{mean_total} (mean of the total biomass), \code{sync}
#' (Loreau and de Mazancourt synchrony index).
#' @examples
#' d <- paradox_sim(alpha = rep(0.5, 10))
#' get_pe(d[-11, -c(1:500)], 10, 5)
#' @useDynLib paradox
get_pe <- function(x, num_pop, t_end) {
    .Call('paradox_get_pe', PACKAGE = 'paradox', x, num_pop, t_end)
}

#' Paradox simulation with PE output for speed YEA
#'
#' @export
paradox_pe_sim <- function(t_end = 1000L, num_pop = 10L, alpha = numeric(), beta = 1/150, m = 0.01, n = 1, sigma = 0.05, q = 0.01, cpar = 1.4, p = 0.5, effort_init = 10, biomass_init = 50, vuln_thresh = 0.1, burnin = 500L, return_ts = FALSE) {
    .Call('paradox_paradox_pe_sim', PACKAGE = 'paradox', t_end, num_pop, alpha, beta, m, n, sigma, q, cpar, p, effort_init, biomass_init, vuln_thresh, burnin, return_ts)
}

#' Simulate biomass and effort trajectories
#'
#' @useDynLib paradox
#' @param t_end Number of time steps to simulate over
#' @param num_pop Number of populations
#' @param alpha alpha parameter in the Shepherd stock-recruit
#' function (density-independent growth). Entered as a numeric vector
#' with one alpha per population.
#' @param beta beta parameter in the Shepherd stock-recruit function
#' (capacity parameter)
#' @param m Natural mortality
#' @param n Depensation parameter in the Shepherd stock-recruit
#' function
#' @param sigma Standard deviation on the simulated alpha values
#' @param q Effectiveness parameter in the effort function
#' @param cpar Operational costs parameter in the effort function
#' @param p Intrinsic value of the fishery parameter in the effort function
#' @param biomas_init Initial population biomass. Recycled across
#' all populations.
#' @param effort_init Initial effort.
#' @author Original model developed by Justin Yeakel. C++ version
#' implemented by Sean Anderson.
#' @return A matrix. Time is incremented along the columns and
#' populations down the rows. The last row represents the effort.
#'
#' @examples
#' d <- paradox_sim(alpha = rep(0.5, 10))
#' matplot(t(d[-11, -c(1:100)]), type = "l", lty = 1)
#' @export
paradox_sim <- function(t_end = 1000L, num_pop = 10L, alpha = numeric(), beta = 1/150, m = 0.01, n = 1, sigma = 0.05, q = 0.01, cpar = 1.4, p = 0.5, effort_init = 10, biomass_init = 50) {
    .Call('paradox_paradox_sim', PACKAGE = 'paradox', t_end, num_pop, alpha, beta, m, n, sigma, q, cpar, p, effort_init, biomass_init)
}

